services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/live_code
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - postgres

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: npm run worker
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/live_code
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: live_code
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d